sudo: false

language: node_js
node_js:
  - "stable"

cache:
  directories:
  - node_modules
  - es
  - lib

jobs:
  include:
    - stage: build
      script:
        - yarn add codecov.io coveralls
        - yarn install
        - yarn test
        - yarn build
      after_success:
        - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
    - stage: deploy
      script: npm install -g nwb 
      deploy:
        provider: npm
        skip_cleanup: true
        email: chachakawooka@googlemail.com
        api_key: $NPM_TOKEN
        on:
          branch: master